app: import-service
service: import-service
frameworkVersion: "3"
plugins:
  - serverless-esbuild
provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  stage: dev
  environment:
    BUCKET_ARN: arn:aws:s3:::import-service-aws-s3
    BUCKET_NAME: import-service-aws-s3
    NODE_OPTIONS: '--enable-source-maps'
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "${self:provider.environment.BUCKET_ARN}"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "${self:provider.environment.BUCKET_ARN}/*"
  logs:
    frameworkLambda: true
    httpApi: true
  httpApi:
    cors:
      allowedHeaders: '*'
      allowedMethods: '*'
functions:
  importProductsFile:
    handler: ./handlers/importProductsFile.default
    events:
      - http:
          path: "/import"
          method: "POST"
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          tracing: true

  importFileParser:
    handler: ./handlers/importFileParser.default
    events:
      - s3:
          bucket: "${self:provider.environment.BUCKET_NAME}"
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
